/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package faconverter;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


/**
 *
 * @author sanad
 */
public class MainFrame extends javax.swing.JFrame {

    private String[] input = {"", "", "", "","", "", "", "","", "", "", ""};
    private String displayImportText = "";

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneContainer = new javax.swing.JTabbedPane();
        HomePageFrame = new javax.swing.JPanel();
        line1Label = new javax.swing.JLabel();
        line2Label = new javax.swing.JLabel();
        line3Label = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        imageLabel1 = new javax.swing.JLabel();
        imageLabel2 = new javax.swing.JLabel();
        imageLabel3 = new javax.swing.JLabel();
        leaderLabel = new javax.swing.JLabel();
        participationLabel = new javax.swing.JLabel();
        partPercentLabel1 = new javax.swing.JLabel();
        partPercentLabel2 = new javax.swing.JLabel();
        partPercentLabel3 = new javax.swing.JLabel();
        FunctionsPageFrame = new javax.swing.JPanel();
        outputPanel = new javax.swing.JPanel();
        inputContainerPanel = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        importButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        rgToNFAButton = new javax.swing.JButton();
        rgToNFANoEpsilonButton = new javax.swing.JButton();
        rgToDFAButton = new javax.swing.JButton();
        rgToMinDFAButton = new javax.swing.JButton();
        testStringsButton = new javax.swing.JButton();
        HelpPageFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        line1Label.setText("TIC2151 Theory of Computation");

        line2Label.setText("Tutorial group TT2L");

        line3Label.setText("Group 1");

        nameLabel1.setText("Member 1");

        nameLabel2.setText("Member 2");

        nameLabel3.setText("Member 3");

        imageLabel1.setBackground(new java.awt.Color(0, 153, 153));
        imageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faconverter/images/42ff1608-aaae-4e45-ba1f-807715f64825.jpg"))); // NOI18N
        imageLabel1.setText("Image 1");
        imageLabel1.setToolTipText("");

        imageLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faconverter/images/869b1338-4c43-4e80-aaf5-01b207dcd124.jpg"))); // NOI18N
        imageLabel2.setText("Image 2");
        imageLabel2.setToolTipText("");

        imageLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faconverter/images/d51d87a8-16fc-402c-a7a2-dc7512b41fd7.jpg"))); // NOI18N
        imageLabel3.setText("Image 3");
        imageLabel3.setToolTipText("");

        leaderLabel.setText("Leader");

        participationLabel.setText("Participation:");

        partPercentLabel1.setText("X%");

        partPercentLabel2.setText("Y%");

        partPercentLabel3.setText("Z%");

        javax.swing.GroupLayout HomePageFrameLayout = new javax.swing.GroupLayout(HomePageFrame);
        HomePageFrame.setLayout(HomePageFrameLayout);
        HomePageFrameLayout.setHorizontalGroup(
            HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageFrameLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Label)
                    .addComponent(line2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePageFrameLayout.createSequentialGroup()
                        .addComponent(participationLabel)
                        .addGap(55, 55, 55)
                        .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePageFrameLayout.createSequentialGroup()
                                .addComponent(partPercentLabel1)
                                .addGap(201, 201, 201)
                                .addComponent(partPercentLabel2)
                                .addGap(177, 177, 177)
                                .addComponent(partPercentLabel3))
                            .addComponent(leaderLabel))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(HomePageFrameLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePageFrameLayout.createSequentialGroup()
                        .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(imageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(imageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePageFrameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(nameLabel1)
                        .addGap(169, 169, 169)
                        .addComponent(nameLabel2)
                        .addGap(150, 150, 150)
                        .addComponent(nameLabel3)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        HomePageFrameLayout.setVerticalGroup(
            HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(line1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line3Label)
                .addGap(35, 35, 35)
                .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(nameLabel2)
                    .addComponent(nameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leaderLabel)
                .addGap(18, 18, 18)
                .addGroup(HomePageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(participationLabel)
                    .addComponent(partPercentLabel1)
                    .addComponent(partPercentLabel2)
                    .addComponent(partPercentLabel3))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        TabbedPaneContainer.addTab("Home", HomePageFrame);

        outputPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        inputContainerPanel.setViewportView(inputTextArea);

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");

        rgToNFAButton.setText("NFA");

        rgToNFANoEpsilonButton.setText("NFA w/o ε ");

        rgToDFAButton.setText("DFA");

        rgToMinDFAButton.setText("Min DFA");

        testStringsButton.setText("Test");

        javax.swing.GroupLayout FunctionsPageFrameLayout = new javax.swing.GroupLayout(FunctionsPageFrame);
        FunctionsPageFrame.setLayout(FunctionsPageFrameLayout);
        FunctionsPageFrameLayout.setHorizontalGroup(
            FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                        .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rgToMinDFAButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                                .addComponent(testStringsButton)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                                .addComponent(rgToDFAButton)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                                .addComponent(rgToNFAButton)
                                .addGap(5, 5, 5)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                        .addComponent(rgToNFANoEpsilonButton)
                        .addGap(18, 18, 18)))
                .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FunctionsPageFrameLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(importButton)
                            .addGap(70, 70, 70)
                            .addComponent(clearButton))
                        .addComponent(inputContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );
        FunctionsPageFrameLayout.setVerticalGroup(
            FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsPageFrameLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(inputContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importButton)
                    .addComponent(clearButton))
                .addGroup(FunctionsPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FunctionsPageFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(FunctionsPageFrameLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(rgToNFAButton)
                        .addGap(18, 18, 18)
                        .addComponent(rgToNFANoEpsilonButton)
                        .addGap(18, 18, 18)
                        .addComponent(rgToDFAButton)
                        .addGap(18, 18, 18)
                        .addComponent(rgToMinDFAButton)
                        .addGap(18, 18, 18)
                        .addComponent(testStringsButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        TabbedPaneContainer.addTab("RG to FA", FunctionsPageFrame);

        javax.swing.GroupLayout HelpPageFrameLayout = new javax.swing.GroupLayout(HelpPageFrame);
        HelpPageFrame.setLayout(HelpPageFrameLayout);
        HelpPageFrameLayout.setHorizontalGroup(
            HelpPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        HelpPageFrameLayout.setVerticalGroup(
            HelpPageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        TabbedPaneContainer.addTab("Help", HelpPageFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPaneContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:
        displayImportText="";
        inputTextArea.setText(displayImportText);

        try{
        BufferedReader reader = new BufferedReader(new FileReader("input.txt"));
        String line;
        int index = 0;  
        while((line = reader.readLine()) != null){
            input[index] = line;
            displayImportText += input[index] + "\n";     
        }
        System.out.println("displayImportText: " + displayImportText); 
        inputTextArea.setText(displayImportText);
        reader.close();

        
   
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_importButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FunctionsPageFrame;
    private javax.swing.JPanel HelpPageFrame;
    private javax.swing.JPanel HomePageFrame;
    private javax.swing.JTabbedPane TabbedPaneContainer;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JLabel imageLabel2;
    private javax.swing.JLabel imageLabel3;
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane inputContainerPanel;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel leaderLabel;
    private javax.swing.JLabel line1Label;
    private javax.swing.JLabel line2Label;
    private javax.swing.JLabel line3Label;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JLabel partPercentLabel1;
    private javax.swing.JLabel partPercentLabel2;
    private javax.swing.JLabel partPercentLabel3;
    private javax.swing.JLabel participationLabel;
    private javax.swing.JButton rgToDFAButton;
    private javax.swing.JButton rgToMinDFAButton;
    private javax.swing.JButton rgToNFAButton;
    private javax.swing.JButton rgToNFANoEpsilonButton;
    private javax.swing.JButton testStringsButton;
    // End of variables declaration//GEN-END:variables
}
